accounts/urls.py
from django.urls import path 
from .views import SignUpView, UserListView, UserPersonalRoom, AdminPanelView


urlpatterns = [
    path('', UserListView.as_view(), name='users_list'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('my-room/', UserPersonalRoom.as_view(), name='p_room'),
    path('admin-panel/', AdminPanelView.as_view(), name='admin_panel'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'


urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('shop.urls', namespace='shop')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    

shop/urls.py
from django.urls import path
from . import views
app_name = 'shop'
urlpatterns = [
    path('', views.home, name='home'),
    path('new-category/', views.CategoryCreate.as_view(), name='category_create'),
    path('new-product/', views.ProductCreate.as_view(), name='product_create'),
    path('delete-category/<int:pk>/', views.CategoryDelete.as_view(), name='category_delete'),
    path('update-category/<int:pk>/', views.CategoryUpdate.as_view(), name='category_update'),
    path('delete-product/<int:pk>/', views.ProductDelete.as_view(), name='product_delete'),
    path('update-product/<int:pk>/', views.ProductUpdate.as_view(), name='product_update'),
    path('new-promo/', views.PromoCreate.as_view(), name='promo_create'),
    path('delete-promo/<int:pk>/', views.PromoDelete.as_view(), name='promo_delete'),
    path('update-promo/<int:pk>/', views.PromoUpdate.as_view(), name='promo_update'),
    path('detail-promo/<int:pk>/<slug:slug>/', views.PromoDetail.as_view(), name='promo_detail'),
    path('shop', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    
    
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

GENDER = (
    ('MALE', 'male'),
    ('FEMALE', 'female')
)


class CustomUser(AbstractUser):
    gender = models.CharField(choices=GENDER, max_length=55, blank=True, null=True)
    birthdate = models.DateTimeField(blank=True, null=True)

    class Meta:
        ordering = ['username']

    def __str__(self):
        return self.username

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    birthdate = forms.DateTimeField(label='Birthdate', 
                                    widget=forms.DateTimeInput(attrs={'type':'date'}))

    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = UserCreationForm.Meta.fields + ('gender', 'birthdate')
    

accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from .forms import CustomUserCreationForm
from .models import CustomUser
from shop.models import Product, Promotion, Category

# Create your views here.
class SignUpView(generic.CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('shop:home')
    template_name = 'registration/signup.html'


class UserListView(generic.ListView):
    model = CustomUser
    context_object_name = 'users'
    template_name = 'accounts/users_list.html'


class UserPersonalRoom(generic.TemplateView):
    template_name = 'accounts/p_room.html'


class AdminPanelView(generic.ListView):
    model = Product
    template_name = 'accounts/admin.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['products'] = Product.objects.all()
        context['promos'] = Promotion.objects.all()
        context['categories'] = Category.objects.all()
        return context

templates/accounts/admin.html
{% extends 'base.html' %}

{% block name %} Administrator's panel{% endblock %}

{% block content %}
    <div class="container">
        <h1 style="text-align: center;margin-top: 20px;font-size: 60px;color: blueviolet;">Admin panel</h1>
        <div style="background-color: blueviolet;">
            <hr style="height: 5px;">
            <div style="display: flex;justify-content: space-around;margin-top: 35px;margin-bottom: 35px;">
                <a href="{% url 'shop:product_create' %}?next={{ request.path }}" class="btn btn-success">Create new product</a>
                <a href="{% url 'shop:promo_create' %}?next={{ request.path }}" class="btn btn-success">Create new promo</a>
                <a href="{% url 'shop:category_create' %}?next={{ request.path }}" class="btn btn-success">Create new category</a>
            </div>
            <hr style="height: 5px;">
        </div>
        <div class="lists" style="display: flex;justify-content: space-around;">
            <div class="card" style="width: 22rem;">
                <div class="card-header" style="border-color: blueviolet;background-color: lightblue;">
                    <h1 style="color: blueviolet;">Products :</h1>
                </div>
                <ul class="list-group list-group-flush" style="border-color: blueviolet;">
                    {% for product in products %}
                        <li class="list-group-item" style="border-color: blueviolet;">
                            <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>  <a href="{% url 'shop:product_delete' product.pk %}?next={{ request.path }}" class="btn" style="color: red;max-width: max-content;">Delete</a>  <a href="{% url 'shop:product_update' product.pk %}?next={{ request.path }}" class="btn" style="color: blue;max-width: max-content;">Edit</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="card" style="width: 22rem;">
                <div class="card-header" style="border-color: blueviolet;background-color: lightblue;">
                    <h1 style="text-align: center; color: blueviolet;">Promos :</h1>
                </div>
                <ul class="list-group list-group-flush" style="border-color: blueviolet;">
                    {% for promo in promos %}
                        <li class="list-group-item" style="border-color: blueviolet;">
                            <a href="{{ promo.get_absolute_url }}">{{ promo.header }}</a>  <a href="{% url 'shop:promo_delete' promo.pk %}?next={{ request.path }}" class="btn" style="color: red;max-width: max-content;">Delete</a>  <a href="{% url 'shop:promo_update' promo.pk %}?next={{ request.path }}" class="btn" style="color: blue;max-width: max-content;">Edit</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="card" style="width: 22rem;">
                <div class="card-header" style="border-color: blueviolet;background-color: lightblue;">
                    <h1 style="text-align: center; color: blueviolet;">Categories :</h1>
                </div>
                <ul class="list-group list-group-flush" style="border-color: blueviolet;">
                    {% for category in categories %}
                        <li class="list-group-item" style="border-color: blueviolet;">
                            <a href="{{ category.get_absolute_url }}">{{ category.name }}</a>  <a href="{% url 'shop:category_delete' category.pk %}?next={{ request.path }}" class="btn" style="color: red;max-width: max-content;">Delete</a>  <a href="{% url 'shop:category_update' category.pk %}?next={{ request.path }}" class="btn" style="color: blue;max-width: max-content;">Edit</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

templates/accounts/p_room.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Personal Room{% endblock %}

{% block content %}
    <h1 style="margin-bottom: 40px; margin-top: 40px;">This is your personal room.</h1>
    <p style="color: blue;">Username = {{ user.username | title }}</p>
    <br>
    <a href="{% url 'logout' %}" class="btn btn-primary" style="margin-top: 20px;">Log Out</a>
    <br style="height: auto;">
    <a href="{% url 'password_change' %}" class="btn btn-primary" style="margin-top: 20px;">Change my password</a>
    <br style="height: auto;">
    <a href="{% url 'password_reset' %}" class="btn btn-primary" style="margin-top: 20px;">Reset my password</a>
{% endblock %}

templates/accounts/users_list.html
{% extends 'base.html' %}
{% load  static %}

{% block title%} Users List{% endblock %}

{% block content %}
    {% for user in users %}
        Username:{{ user.username }}
        Gender:{{ user.gender }}
        id:{{ user.id }}
        <br>
    {% endfor %}
{% endblock %}